name: Upload code coverage

on:
  workflow_run:
    workflows: [Test]
    types: [completed]
    branches: [master]

jobs:
  upload-code-coverage:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18.x

      - name: Run tests and write coverprofile
        shell: bash
        run: |
          go test -v -race -covermode=atomic -coverprofile=profile.out -coverpkg ./ ./test

      - name: Upload testcoverage to codecov.io
        uses: codecov/codecov-action@v1
        with:
          file: ./profile.out
          fail_ci_if_error: true